import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

import "./globals.css";
import { Outfit } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  // variable: "--font-outfit",
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className} antialiased`}
        >
          <Provider>
            {children}
            <Toaster />
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}

// Video 2:45:13 --> https://youtu.be/lHFlpc5auDY?t=10464 // 2:24:44
    // Logo: 49:16
    // "" src passed error at 2:54:24 (Doesn't look like the frameList is saving/updating)(Not loading updated video on refresh?)

// Using 'shadcn/ui' for components. You can add new ones with "npx shadcn@latest add [component]"

// Run 'npx drizzle-kit studio' for local backend

// Using Clerk for authenticattion

// Using Neon + Drizzle for database

// Remotion for video generation

// Aspect ratios - 16:9, 9:16, 1:1, 4:3, 3:4

// Clicking first frame stays on 2 second mark? --> https://youtu.be/lHFlpc5auDY?t=7398